# Generated by Django 4.0.4 on 2022-11-01 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': 'Тип события', 'verbose_name_plural': 'Типы события'},
        ),
    ]
