# Generated by Django 4.0.4 on 2022-10-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Ид.')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование станции')),
                ('short_name', models.CharField(default='-', max_length=10, verbose_name='Короткое наименование станции')),
                ('company', models.CharField(blank=True, max_length=50, null=True, verbose_name='Генерирующая компания')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес нахождения')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
            ],
        ),
    ]
