# Generated by Django 4.0.4 on 2022-10-28 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование компании')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Ид.')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование станции')),
                ('short_name', models.CharField(default='-', max_length=10, verbose_name='Короткое наименование станции')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес нахождения')),
                ('image', models.ImageField(blank=True, upload_to='img/', verbose_name='Изображение')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.company')),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(default='Газотурбинная установка', max_length=50, verbose_name='Тип машины')),
                ('name', models.CharField(default='-', max_length=10, verbose_name='Имя установки')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование установки')),
                ('short_name', models.CharField(max_length=10, verbose_name='Короткое наименование установки')),
                ('station_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Станционный номер')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.unittype')),
            ],
        ),
    ]
