# Generated by Django 4.0.4 on 2022-11-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Станция', 'verbose_name_plural': 'Станции'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Установка', 'verbose_name_plural': 'Установки'},
        ),
        migrations.AlterModelOptions(
            name='unittype',
            options={'verbose_name': 'Тип установки', 'verbose_name_plural': 'Типы установок'},
        ),
        migrations.AlterField(
            model_name='station',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Короткое наименование станции'),
        ),
    ]
