# Generated by Django 4.0.4 on 2022-10-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
